module.exports = [
  "Accessible Media Production",
  "Advanced Police Studies",
  "Advanced Security Management",
  "Advertising and Marketing Communications Management",
  "Analytics for Business Decision Making",
  "Animation 3D",
  "Applied Music",
  "Applied Music for Bass",
  "Applied Music for Classical Piano",
  "Applied Music for Classical Strings and Guitar",
  "Applied Music for Classical Voice",
  "Applied Music for Classical Winds and Brass",
  "Applied Music for Contemporary Brass and Winds",
  "Applied Music for Contemporary Guitar",
  "Applied Music for Contemporary Piano",
  "Applied Music for Contemporary Voice",
  "Applied Music for Drums and Percussion",
  "Applied Music for Other",
  "Applied Music Preparatory",
  "Architectural Technician",
  "Architectural Technology",
  "Art and Design Foundations",
  "Augmented and Virtual Reality Innovation Certificate",
  "Autism and Behavioural Science",
  "Auto Body and Collision Damage Repairer",
  "Automotive Service Educational Program known as A.S.E.P.",
  "Automotive Service Technician",
  "Aviation Technician for Aircraft Maintenance",
  "Aviation Technician for Aircraft Structures",
  "Aviation Technician for Avionics Maintenance",
  "Bachelor of Technology Partnership: Combined Degree Program",
  "Bachelor of Technology Partnership: Degree Completion Program",
  "Biotechnology Health",
  "Biotechnology",
  "Biotechnology Advanced",
  "Brain Disorders Management",
  "Broadcasting Radio",
  "Broadcasting   Television and Communications Media",
  "Business General",
  "Business Accounting",
  "Business Financial Services",
  "Business Marketing",
  "Business Administration",
  "Business Administration Accounting",
  "Business Administration  Human Resources",
  "Business Administration Marketing",
  "Business Analysis",
  "Business Fundamentals Small Business",
  "Canadian Health Care for Foreign Trained Professionals",
  "Cardiovascular Technology",
  "Career Pathways",
  "Chemical Engineering Technology",
  "Child and Youth Care",
  "Child and Youth Worker",
  "Child Development Practitioner",
  "Civil Engineering Technician",
  "Civil Engineering Technology",
  "Civil Engineering Technology Transportation",
  "Communications Media Practices",
  "Community and Justice Services",
  "Community and Social Services Management",
  "Community Integration through Co operative Education",
  "Community Pharmacy Assistant",
  "Computer Engineering Technician",
  "Computer Engineering Technician Mechatronic Systems",
  "Computer Engineering Technology",
  "Computer Engineering Technology Mechatronic Systems",
  "Computer Systems Technician Network Systems",
  "Computer Systems Technician Software Support",
  "Computer Systems Technology Network Engineering and Security Analyst",
  "Computer Systems Technology Software Development",
  "Concurrent Disorders",
  "Construction Engineering Technician",
  "Construction Engineering Technician Building Renovation",
  "Construction Techniques",
  "Construction Techniques  Plumbing",
  "Creative Arts Business",
  "Cyber Security Analytics",
  "Developmental Service Worker",
  "Diagnostic Cardiac Sonography",
  "Diploma RPN to BScN Degree",
  "Early Childhood Education Intensive",
  "Early Childhood Education",
  "Educational Support Intensive",
  "Educational Support",
  "Electrical Engineering Technician Power",
  "Electrical Engineering Technology",
  "Electrician Construction and Maintenance",
  "Elevating Devices Mechanic",
  "Energy Systems Engineering Technology",
  "Environmental Technician",
  "Expressive Arts",
  "Gas and Oil Burner Technician two",
  "General Arts and Science English for Academic Purposes Domestic",
  "General Arts and Science English for Academic Purposes International",
  "General Arts and Science Certificate College Transfer",
  "General Arts and Science Certificate University Transfer",
  "General Carpenter",
  "General Machinist",
  "Global Business Management International Only",
  "Global Business Management Family Enterprise International Only",
  "Graphic Design",
  "Health Wellness and Fitness",
  "Heating, Refrigeration and Air Conditioning Techniques",
  "Horticulture Technician",
  "Human Resources Management",
  "Human Services Foundation",
  "Industrial Electrician",
  "Industrial Mechanic Millwright",
  "Instrumentation Control and Control Technician",
  "Insurance",
  "International Business Management",
  "Journalism",
  "Learning Disabilities Specialist",
  "Manufacturing Engineering Technician Automation Industrial Mechanic Millwright",
  "Massage Therapy",
  "Mechanical Engineering Technology",
  "Mechanical Technician Elevating Devices",
  "Mechanical Techniques Advanced Manufacturing Operations",
  "Mechanical Techniques Cabinetry",
  "Mechanical Techniques Electrical Monitoring and Systems",
  "Mechanical Techniques Plumbing",
  "Mechanical Techniques Welding and Fabrication",
  "Medical Radiation Sciences",
  "Mental Health and Disability Management",
  "Metal Fabricator Fitter",
  "Motive Power Fundamentals",
  "Motive Power Technician",
  "Multimedia Storytelling",
  "Nursing B S c N",
  "Occupational Therapist Assistant and Physiotherapist Assistant",
  "Office Administration Executive",
  "Office Administration General",
  "Office Administration Health Services",
  "Office Administration Legal",
  "Paralegal",
  "Personal Support Worker",
  "Pharmacy Technician",
  "Photography Still and Motion",
  "Plumber",
  "Police Foundations",
  "Power Engineering Techniques third Class",
  "Power Engineering Techniques",
  "Practical Nursing P S W to P N Bridging Stream",
  "Practical Nursing",
  "Pre Health Sciences Pathway to Advanced Diplomas and Degrees",
  "Pre Health Sciences Pathway to Certificates and Diplomas",
  "Pre Justice",
  "Pre Media and Entertainment",
  "Pre Technology",
  "Protection, Security and Investigation",
  "Public Relations",
  "Quality Engineering Technician Non Destructive Evaluation",
  "Recreation Therapy Intensive",
  "Recreation Therapy",
  "Refrigeration and Air Conditioning Systems Mechanic",
  "Residential Air Conditioning Systems Mechanic",
  "Sheet Metal Worker",
  "Social Service Worker Intensive",
  "Social Service Worker",
  "Steamfitter",
  "Supply Chain Management",
  "Tourism",
  "Truck and Coach Technician",
  "Urban and Regional Planning Technician Geographic Information Systems",
  "Utilities Systems Operator",
  "Virtual Reality Multimedia Production",
  "Welder"
];